/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCalendarWidget>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page_4;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_7;
    QWidget *page;
    QTabWidget *tabWidget;
    QWidget *tab;
    QGroupBox *groupBox;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLineEdit *le_id;
    QLineEdit *le_nom;
    QLineEdit *le_prix;
    QPushButton *pb_ajouter;
    QPushButton *pb_modifier;
    QComboBox *comboBoxCategory;
    QLineEdit *le_quantite;
    QLabel *label_5;
    QWidget *tab_2;
    QTableView *tab_produit;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_4;
    QPushButton *pushButtonGenererPDF;
    QWidget *tab_3;
    QGroupBox *groupBox_2;
    QLabel *label_4;
    QLineEdit *lineEdit;
    QPushButton *pb_supprimer;
    QPushButton *pushButton_8;
    QWidget *tab_4;
    QLineEdit *le_id_rech;
    QTableView *tab_rech;
    QLabel *label_7;
    QLineEdit *le_nom_rech;
    QWidget *tab_9;
    QPushButton *pushButtonStatsCategorie;
    QTableView *tab_stat;
    QWidget *tab_5;
    QTableView *tab_alertes;
    QPushButton *pushButtonAfficherAlertes;
    QCommandLinkButton *pushButtonAjouterStock;
    QWidget *page_2;
    QTabWidget *ajouter;
    QWidget *tab_6;
    QLabel *label_16;
    QGroupBox *groupBox_3;
    QLabel *label_6;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_11;
    QLabel *label_10;
    QLabel *label_20;
    QLabel *label_12;
    QLabel *label_19;
    QLineEdit *le_nom_2;
    QLineEdit *le_prenom;
    QLineEdit *l_id;
    QLineEdit *le_produit;
    QLineEdit *le_numero;
    QLineEdit *id_prod;
    QComboBox *calculatePaymentStatistics;
    QPushButton *pb_valider;
    QPushButton *modif_2;
    QDateEdit *dateEdit;
    QLabel *label_13;
    QLineEdit *prix;
    QTableView *tableView_2;
    QPushButton *recherche_2;
    QComboBox *comboBox_3;
    QLineEdit *cherche_2;
    QPushButton *tri_2;
    QComboBox *comboBox_4;
    QPushButton *exel_2;
    QPushButton *historique_2;
    QPushButton *pdf_2;
    QLabel *label_14;
    QPushButton *supp_3;
    QLineEdit *supp_4;
    QPushButton *pushButton_9;
    QWidget *Afficher;
    QCalendarWidget *calendarWidget;
    QTableView *listView;
    QWidget *tab_7;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *verticalLayout;
    QPushButton *pushButtonstat;
    QWidget *chat;
    QLineEdit *envoyer_2;
    QPushButton *envoyer;
    QLabel *label_chatbot_response;
    QWidget *tab_8;
    QLabel *label_15;
    QLabel *label_17;
    QPushButton *pushButton_3;
    QPushButton *pushButton_6;
    QPushButton *pushButton_4;
    QLabel *label_18;
    QLabel *label_21;
    QPushButton *pushButton_5;
    QWidget *page_3;
    QTabWidget *OpTabWidget;
    QWidget *CREATION;
    QLabel *OpLabel;
    QLabel *OpLabel_6;
    QLabel *OpLabel_2;
    QLabel *OpLabel_4;
    QSpinBox *dureeSpinBox;
    QLabel *OpLabel_3;
    QSpinBox *IdSpinBox;
    QComboBox *typeComboBox;
    QLabel *OpLabel_5;
    QLabel *OpLabel_17;
    QLineEdit *EtatlineEdit_1;
    QPushButton *creationBtn;
    QWidget *AFFICHAGE;
    QLabel *OpLabel_7;
    QLabel *OpLabel_8;
    QGroupBox *groupBox_4;
    QComboBox *choixComboBox;
    QLineEdit *RechlineEdit;
    QTableView *tableViewAffichage;
    QPushButton *rechercheBtn;
    QPushButton *sortBtn;
    QPushButton *PDFBtn;
    QWidget *MODIFICATION;
    QLabel *OpLabel_9;
    QLabel *OpLabel_11;
    QLabel *OpLabel_12;
    QSpinBox *modifSpinBox;
    QLabel *OpLabel_13;
    QLabel *OpLabel_18;
    QSpinBox *modifSpinBoxId;
    QComboBox *ModifTypeComboBox;
    QLabel *OpLabel_20;
    QLineEdit *modifDureeLineEdit;
    QLineEdit *modifEtatLineEdit;
    QPushButton *modifBtn;
    QLabel *OpLabel_19;
    QWidget *SUPPRESSION;
    QLabel *OpLabel_10;
    QLabel *OpLabel_14;
    QLabel *OpLabel_15;
    QSpinBox *suppSpinBox;
    QPushButton *suppBtn;
    QWidget *STATISTIQUE;
    QLabel *OpLabel_22;
    QLabel *OpLabel_23;
    QGroupBox *groupBox_5;
    QTableView *StatOpTableView;
    QPushButton *StatTypeBtn;
    QPushButton *statEtatBtn;
    QWidget *SUIVI;
    QLabel *OpLabel_26;
    QLabel *OpLabel_30;
    QGroupBox *groupBox_6;
    QPushButton *SuiviBtn;
    QLineEdit *suiviLineEdit;
    QStackedWidget *stackedWidget_2;
    QWidget *page_5;
    QWidget *page_6;
    QWidget *page_7;
    QWidget *page_8;
    QLabel *OpLabel_16;
    QLabel *OpLabel_21;
    QWidget *ACCEPTER_OPERATION;
    QLabel *OpLabel_27;
    QGroupBox *groupBox_7;
    QLabel *OpLabel_24;
    QLabel *OpLabel_25;
    QPushButton *AccepteOpBtn;
    QLabel *OpLabel_31;
    QWidget *MESUREDEPOIDS;
    QLabel *OpLabel_28;
    QGroupBox *groupBox_8;
    QLabel *OpLabel_29;
    QLineEdit *lineEdit_5;
    QPushButton *pushButton_12;
    QLabel *OpLabel_32;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1134, 737);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(10, 9, 1091, 641));
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        pushButton = new QPushButton(page_4);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(210, 70, 211, 61));
        pushButton_2 = new QPushButton(page_4);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(210, 160, 211, 61));
        pushButton_7 = new QPushButton(page_4);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(210, 260, 211, 61));
        stackedWidget->addWidget(page_4);
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        tabWidget = new QTabWidget(page);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(80, 20, 941, 551));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 20, 821, 441));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(30, 40, 61, 16));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(30, 100, 56, 16));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(30, 150, 56, 16));
        le_id = new QLineEdit(groupBox);
        le_id->setObjectName(QStringLiteral("le_id"));
        le_id->setGeometry(QRect(100, 40, 113, 22));
        le_nom = new QLineEdit(groupBox);
        le_nom->setObjectName(QStringLiteral("le_nom"));
        le_nom->setGeometry(QRect(100, 90, 113, 22));
        le_prix = new QLineEdit(groupBox);
        le_prix->setObjectName(QStringLiteral("le_prix"));
        le_prix->setGeometry(QRect(100, 140, 113, 22));
        pb_ajouter = new QPushButton(groupBox);
        pb_ajouter->setObjectName(QStringLiteral("pb_ajouter"));
        pb_ajouter->setGeometry(QRect(320, 220, 93, 28));
        QPalette palette;
        QBrush brush(QColor(0, 0, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush1(QColor(240, 240, 240, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_ajouter->setPalette(palette);
        pb_modifier = new QPushButton(groupBox);
        pb_modifier->setObjectName(QStringLiteral("pb_modifier"));
        pb_modifier->setGeometry(QRect(490, 220, 93, 28));
        comboBoxCategory = new QComboBox(groupBox);
        comboBoxCategory->setObjectName(QStringLiteral("comboBoxCategory"));
        comboBoxCategory->setGeometry(QRect(100, 230, 111, 22));
        le_quantite = new QLineEdit(groupBox);
        le_quantite->setObjectName(QStringLiteral("le_quantite"));
        le_quantite->setGeometry(QRect(100, 190, 113, 22));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 190, 61, 16));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tab_produit = new QTableView(tab_2);
        tab_produit->setObjectName(QStringLiteral("tab_produit"));
        tab_produit->setGeometry(QRect(5, 41, 621, 341));
        checkBox = new QCheckBox(tab_2);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(620, 10, 83, 20));
        checkBox_2 = new QCheckBox(tab_2);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(530, 10, 83, 20));
        checkBox_3 = new QCheckBox(tab_2);
        checkBox_3->setObjectName(QStringLiteral("checkBox_3"));
        checkBox_3->setGeometry(QRect(440, 10, 83, 20));
        checkBox_4 = new QCheckBox(tab_2);
        checkBox_4->setObjectName(QStringLiteral("checkBox_4"));
        checkBox_4->setGeometry(QRect(350, 10, 83, 20));
        pushButtonGenererPDF = new QPushButton(tab_2);
        pushButtonGenererPDF->setObjectName(QStringLiteral("pushButtonGenererPDF"));
        pushButtonGenererPDF->setGeometry(QRect(650, 190, 93, 28));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        groupBox_2 = new QGroupBox(tab_3);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(0, 30, 761, 371));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(30, 80, 56, 16));
        lineEdit = new QLineEdit(groupBox_2);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(100, 80, 113, 22));
        pb_supprimer = new QPushButton(groupBox_2);
        pb_supprimer->setObjectName(QStringLiteral("pb_supprimer"));
        pb_supprimer->setGeometry(QRect(120, 150, 93, 28));
        pushButton_8 = new QPushButton(tab_3);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(830, 10, 61, 28));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        le_id_rech = new QLineEdit(tab_4);
        le_id_rech->setObjectName(QStringLiteral("le_id_rech"));
        le_id_rech->setGeometry(QRect(140, 140, 113, 22));
        tab_rech = new QTableView(tab_4);
        tab_rech->setObjectName(QStringLiteral("tab_rech"));
        tab_rech->setGeometry(QRect(280, 20, 471, 371));
        label_7 = new QLabel(tab_4);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(80, 40, 81, 20));
        le_nom_rech = new QLineEdit(tab_4);
        le_nom_rech->setObjectName(QStringLiteral("le_nom_rech"));
        le_nom_rech->setGeometry(QRect(140, 200, 113, 22));
        tabWidget->addTab(tab_4, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        pushButtonStatsCategorie = new QPushButton(tab_9);
        pushButtonStatsCategorie->setObjectName(QStringLiteral("pushButtonStatsCategorie"));
        pushButtonStatsCategorie->setGeometry(QRect(110, 140, 93, 28));
        tab_stat = new QTableView(tab_9);
        tab_stat->setObjectName(QStringLiteral("tab_stat"));
        tab_stat->setGeometry(QRect(260, 20, 471, 371));
        tabWidget->addTab(tab_9, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        tab_alertes = new QTableView(tab_5);
        tab_alertes->setObjectName(QStringLiteral("tab_alertes"));
        tab_alertes->setGeometry(QRect(170, 50, 491, 191));
        pushButtonAfficherAlertes = new QPushButton(tab_5);
        pushButtonAfficherAlertes->setObjectName(QStringLiteral("pushButtonAfficherAlertes"));
        pushButtonAfficherAlertes->setGeometry(QRect(30, 50, 93, 28));
        QPalette palette1;
        QBrush brush2(QColor(0, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush3(QColor(127, 127, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush3);
        QBrush brush4(QColor(63, 63, 255, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        QBrush brush5(QColor(0, 0, 127, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush5);
        QBrush brush6(QColor(0, 0, 170, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush2);
        QBrush brush7(QColor(255, 255, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        QBrush brush9(QColor(0, 0, 0, 128));
        brush9.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        pushButtonAfficherAlertes->setPalette(palette1);
        pushButtonAjouterStock = new QCommandLinkButton(tab_5);
        pushButtonAjouterStock->setObjectName(QStringLiteral("pushButtonAjouterStock"));
        pushButtonAjouterStock->setGeometry(QRect(40, 270, 301, 41));
        tabWidget->addTab(tab_5, QString());
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        ajouter = new QTabWidget(page_2);
        ajouter->setObjectName(QStringLiteral("ajouter"));
        ajouter->setGeometry(QRect(0, 0, 1071, 651));
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        label_16 = new QLabel(tab_6);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(780, 350, 351, 291));
        label_16->setPixmap(QPixmap(QString::fromUtf8("../../../../Downloads/top-view-engagement-rings-with-copy-space.jpg")));
        label_16->setScaledContents(true);
        groupBox_3 = new QGroupBox(tab_6);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(0, 10, 441, 341));
        label_6 = new QLabel(groupBox_3);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 30, 71, 20));
        label_6->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        label_8 = new QLabel(groupBox_3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 60, 81, 16));
        label_8->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(0, 90, 141, 16));
        label_9->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        label_11 = new QLabel(groupBox_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 120, 111, 21));
        label_11->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 150, 201, 21));
        label_10->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        label_20 = new QLabel(groupBox_3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 210, 121, 21));
        label_20->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        label_12 = new QLabel(groupBox_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 180, 121, 21));
        label_12->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        label_19 = new QLabel(groupBox_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 240, 71, 21));
        label_19->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        le_nom_2 = new QLineEdit(groupBox_3);
        le_nom_2->setObjectName(QStringLiteral("le_nom_2"));
        le_nom_2->setGeometry(QRect(230, 20, 151, 21));
        le_prenom = new QLineEdit(groupBox_3);
        le_prenom->setObjectName(QStringLiteral("le_prenom"));
        le_prenom->setGeometry(QRect(230, 50, 151, 21));
        l_id = new QLineEdit(groupBox_3);
        l_id->setObjectName(QStringLiteral("l_id"));
        l_id->setGeometry(QRect(230, 80, 151, 21));
        le_produit = new QLineEdit(groupBox_3);
        le_produit->setObjectName(QStringLiteral("le_produit"));
        le_produit->setGeometry(QRect(230, 110, 151, 21));
        le_numero = new QLineEdit(groupBox_3);
        le_numero->setObjectName(QStringLiteral("le_numero"));
        le_numero->setGeometry(QRect(230, 150, 151, 21));
        id_prod = new QLineEdit(groupBox_3);
        id_prod->setObjectName(QStringLiteral("id_prod"));
        id_prod->setGeometry(QRect(230, 180, 151, 21));
        calculatePaymentStatistics = new QComboBox(groupBox_3);
        calculatePaymentStatistics->setObjectName(QStringLiteral("calculatePaymentStatistics"));
        calculatePaymentStatistics->setGeometry(QRect(230, 210, 151, 21));
        calculatePaymentStatistics->setStyleSheet(QStringLiteral("font: 75 10pt \"Segoe UI\";"));
        pb_valider = new QPushButton(groupBox_3);
        pb_valider->setObjectName(QStringLiteral("pb_valider"));
        pb_valider->setGeometry(QRect(0, 300, 171, 31));
        pb_valider->setStyleSheet(QLatin1String("font: 16pt \"MS Shell Dlg 2\";\n"
";"));
        modif_2 = new QPushButton(groupBox_3);
        modif_2->setObjectName(QStringLiteral("modif_2"));
        modif_2->setGeometry(QRect(200, 300, 171, 31));
        modif_2->setStyleSheet(QLatin1String("font: 16pt \"MS Shell Dlg 2\";\n"
";"));
        dateEdit = new QDateEdit(groupBox_3);
        dateEdit->setObjectName(QStringLiteral("dateEdit"));
        dateEdit->setGeometry(QRect(230, 240, 151, 22));
        label_13 = new QLabel(groupBox_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 270, 56, 16));
        label_13->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        prix = new QLineEdit(groupBox_3);
        prix->setObjectName(QStringLiteral("prix"));
        prix->setGeometry(QRect(230, 270, 151, 21));
        tableView_2 = new QTableView(tab_6);
        tableView_2->setObjectName(QStringLiteral("tableView_2"));
        tableView_2->setGeometry(QRect(450, 110, 311, 291));
        recherche_2 = new QPushButton(tab_6);
        recherche_2->setObjectName(QStringLiteral("recherche_2"));
        recherche_2->setGeometry(QRect(750, 60, 171, 41));
        recherche_2->setStyleSheet(QLatin1String("font: 16pt \"MS Shell Dlg 2\";\n"
";"));
        comboBox_3 = new QComboBox(tab_6);
        comboBox_3->setObjectName(QStringLiteral("comboBox_3"));
        comboBox_3->setGeometry(QRect(470, 60, 131, 41));
        cherche_2 = new QLineEdit(tab_6);
        cherche_2->setObjectName(QStringLiteral("cherche_2"));
        cherche_2->setGeometry(QRect(610, 60, 131, 41));
        tri_2 = new QPushButton(tab_6);
        tri_2->setObjectName(QStringLiteral("tri_2"));
        tri_2->setGeometry(QRect(470, 440, 131, 41));
        tri_2->setStyleSheet(QLatin1String("font: 16pt \"MS Shell Dlg 2\";\n"
";"));
        comboBox_4 = new QComboBox(tab_6);
        comboBox_4->setObjectName(QStringLiteral("comboBox_4"));
        comboBox_4->setGeometry(QRect(600, 440, 91, 41));
        exel_2 = new QPushButton(tab_6);
        exel_2->setObjectName(QStringLiteral("exel_2"));
        exel_2->setGeometry(QRect(980, 170, 81, 41));
        exel_2->setStyleSheet(QStringLiteral("font: 16pt \"MS Shell Dlg 2\";"));
        historique_2 = new QPushButton(tab_6);
        historique_2->setObjectName(QStringLiteral("historique_2"));
        historique_2->setGeometry(QRect(710, 440, 151, 41));
        historique_2->setStyleSheet(QStringLiteral("font: 16pt \"MS Shell Dlg 2\";"));
        pdf_2 = new QPushButton(tab_6);
        pdf_2->setObjectName(QStringLiteral("pdf_2"));
        pdf_2->setGeometry(QRect(980, 230, 81, 41));
        pdf_2->setStyleSheet(QLatin1String("font: 16pt \"MS Shell Dlg 2\";\n"
";"));
        label_14 = new QLabel(tab_6);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(470, 510, 111, 31));
        label_14->setStyleSheet(QStringLiteral("font: 12pt \"NSimSun\";"));
        supp_3 = new QPushButton(tab_6);
        supp_3->setObjectName(QStringLiteral("supp_3"));
        supp_3->setGeometry(QRect(720, 500, 141, 41));
        supp_3->setStyleSheet(QLatin1String("font: 16pt \"MS Shell Dlg 2\";\n"
";"));
        supp_4 = new QLineEdit(tab_6);
        supp_4->setObjectName(QStringLiteral("supp_4"));
        supp_4->setGeometry(QRect(590, 510, 121, 31));
        pushButton_9 = new QPushButton(tab_6);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(990, 0, 61, 28));
        ajouter->addTab(tab_6, QString());
        Afficher = new QWidget();
        Afficher->setObjectName(QStringLiteral("Afficher"));
        calendarWidget = new QCalendarWidget(Afficher);
        calendarWidget->setObjectName(QStringLiteral("calendarWidget"));
        calendarWidget->setGeometry(QRect(40, 20, 751, 301));
        listView = new QTableView(Afficher);
        listView->setObjectName(QStringLiteral("listView"));
        listView->setGeometry(QRect(30, 340, 761, 192));
        ajouter->addTab(Afficher, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        verticalLayoutWidget = new QWidget(tab_7);
        verticalLayoutWidget->setObjectName(QStringLiteral("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(110, 50, 701, 431));
        verticalLayout = new QVBoxLayout(verticalLayoutWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        pushButtonstat = new QPushButton(tab_7);
        pushButtonstat->setObjectName(QStringLiteral("pushButtonstat"));
        pushButtonstat->setGeometry(QRect(860, 370, 151, 41));
        ajouter->addTab(tab_7, QString());
        chat = new QWidget();
        chat->setObjectName(QStringLiteral("chat"));
        envoyer_2 = new QLineEdit(chat);
        envoyer_2->setObjectName(QStringLiteral("envoyer_2"));
        envoyer_2->setGeometry(QRect(330, 300, 113, 22));
        envoyer = new QPushButton(chat);
        envoyer->setObjectName(QStringLiteral("envoyer"));
        envoyer->setGeometry(QRect(490, 300, 93, 28));
        label_chatbot_response = new QLabel(chat);
        label_chatbot_response->setObjectName(QStringLiteral("label_chatbot_response"));
        label_chatbot_response->setGeometry(QRect(320, 60, 461, 221));
        ajouter->addTab(chat, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        label_15 = new QLabel(tab_8);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(300, 170, 47, 13));
        label_17 = new QLabel(tab_8);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(300, 250, 47, 13));
        pushButton_3 = new QPushButton(tab_8);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(380, 240, 41, 23));
        pushButton_6 = new QPushButton(tab_8);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(370, 160, 61, 23));
        pushButton_4 = new QPushButton(tab_8);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(470, 160, 51, 23));
        label_18 = new QLabel(tab_8);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(300, 210, 51, 16));
        label_21 = new QLabel(tab_8);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(390, 210, 47, 13));
        pushButton_5 = new QPushButton(tab_8);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(460, 240, 41, 23));
        ajouter->addTab(tab_8, QString());
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        OpTabWidget = new QTabWidget(page_3);
        OpTabWidget->setObjectName(QStringLiteral("OpTabWidget"));
        OpTabWidget->setGeometry(QRect(0, 30, 1061, 631));
        CREATION = new QWidget();
        CREATION->setObjectName(QStringLiteral("CREATION"));
        OpLabel = new QLabel(CREATION);
        OpLabel->setObjectName(QStringLiteral("OpLabel"));
        OpLabel->setGeometry(QRect(-20, -10, 781, 491));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        OpLabel->setPalette(palette2);
        OpLabel->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel->setScaledContents(true);
        OpLabel_6 = new QLabel(CREATION);
        OpLabel_6->setObjectName(QStringLiteral("OpLabel_6"));
        OpLabel_6->setGeometry(QRect(280, 220, 101, 31));
        QFont font;
        font.setFamily(QStringLiteral("Arial"));
        font.setPointSize(11);
        font.setBold(true);
        font.setUnderline(true);
        font.setWeight(75);
        OpLabel_6->setFont(font);
        OpLabel_6->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: transparent;"));
        OpLabel_2 = new QLabel(CREATION);
        OpLabel_2->setObjectName(QStringLiteral("OpLabel_2"));
        OpLabel_2->setEnabled(true);
        OpLabel_2->setGeometry(QRect(160, 10, 411, 51));
        QFont font1;
        font1.setFamily(QStringLiteral("Arial"));
        font1.setPointSize(22);
        font1.setBold(false);
        font1.setUnderline(true);
        font1.setWeight(50);
        OpLabel_2->setFont(font1);
        OpLabel_2->setStyleSheet(QLatin1String("background-color: transparent;\n"
"\n"
""));
        OpLabel_2->setTextFormat(Qt::AutoText);
        OpLabel_4 = new QLabel(CREATION);
        OpLabel_4->setObjectName(QStringLiteral("OpLabel_4"));
        OpLabel_4->setGeometry(QRect(20, 134, 251, 31));
        QFont font2;
        font2.setFamily(QStringLiteral("Arial"));
        font2.setPointSize(16);
        OpLabel_4->setFont(font2);
        OpLabel_4->setStyleSheet(QStringLiteral("background-color: transparent;"));
        dureeSpinBox = new QSpinBox(CREATION);
        dureeSpinBox->setObjectName(QStringLiteral("dureeSpinBox"));
        dureeSpinBox->setGeometry(QRect(430, 194, 311, 31));
        dureeSpinBox->setStyleSheet(QStringLiteral("font: 11pt \"Arial\";"));
        OpLabel_3 = new QLabel(CREATION);
        OpLabel_3->setObjectName(QStringLiteral("OpLabel_3"));
        OpLabel_3->setGeometry(QRect(20, 74, 211, 31));
        OpLabel_3->setFont(font2);
        OpLabel_3->setStyleSheet(QStringLiteral("background-color: transparent;"));
        IdSpinBox = new QSpinBox(CREATION);
        IdSpinBox->setObjectName(QStringLiteral("IdSpinBox"));
        IdSpinBox->setGeometry(QRect(430, 74, 311, 31));
        IdSpinBox->setStyleSheet(QStringLiteral("font: 11pt \"Arial\";"));
        typeComboBox = new QComboBox(CREATION);
        typeComboBox->setObjectName(QStringLiteral("typeComboBox"));
        typeComboBox->setGeometry(QRect(430, 134, 311, 31));
        typeComboBox->setStyleSheet(QStringLiteral("font: 11pt \"Arial\";"));
        OpLabel_5 = new QLabel(CREATION);
        OpLabel_5->setObjectName(QStringLiteral("OpLabel_5"));
        OpLabel_5->setGeometry(QRect(20, 194, 391, 31));
        OpLabel_5->setFont(font2);
        OpLabel_5->setStyleSheet(QStringLiteral("background-color: transparent;"));
        OpLabel_17 = new QLabel(CREATION);
        OpLabel_17->setObjectName(QStringLiteral("OpLabel_17"));
        OpLabel_17->setGeometry(QRect(20, 270, 341, 31));
        OpLabel_17->setFont(font2);
        OpLabel_17->setStyleSheet(QStringLiteral("background-color: transparent;"));
        EtatlineEdit_1 = new QLineEdit(CREATION);
        EtatlineEdit_1->setObjectName(QStringLiteral("EtatlineEdit_1"));
        EtatlineEdit_1->setGeometry(QRect(430, 270, 311, 31));
        creationBtn = new QPushButton(CREATION);
        creationBtn->setObjectName(QStringLiteral("creationBtn"));
        creationBtn->setGeometry(QRect(300, 370, 121, 41));
        QFont font3;
        font3.setFamily(QStringLiteral("Arial"));
        font3.setPointSize(11);
        creationBtn->setFont(font3);
        OpTabWidget->addTab(CREATION, QString());
        AFFICHAGE = new QWidget();
        AFFICHAGE->setObjectName(QStringLiteral("AFFICHAGE"));
        OpLabel_7 = new QLabel(AFFICHAGE);
        OpLabel_7->setObjectName(QStringLiteral("OpLabel_7"));
        OpLabel_7->setGeometry(QRect(0, 0, 781, 491));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        OpLabel_7->setPalette(palette3);
        OpLabel_7->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel_7->setScaledContents(true);
        OpLabel_8 = new QLabel(AFFICHAGE);
        OpLabel_8->setObjectName(QStringLiteral("OpLabel_8"));
        OpLabel_8->setGeometry(QRect(200, 30, 291, 41));
        QFont font4;
        font4.setFamily(QStringLiteral("Arial"));
        font4.setPointSize(22);
        font4.setUnderline(true);
        OpLabel_8->setFont(font4);
        OpLabel_8->setStyleSheet(QStringLiteral("background-color: transparent;"));
        groupBox_4 = new QGroupBox(AFFICHAGE);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(20, 130, 661, 321));
        choixComboBox = new QComboBox(groupBox_4);
        choixComboBox->setObjectName(QStringLiteral("choixComboBox"));
        choixComboBox->setGeometry(QRect(300, 10, 171, 31));
        choixComboBox->setFont(font3);
        RechlineEdit = new QLineEdit(groupBox_4);
        RechlineEdit->setObjectName(QStringLiteral("RechlineEdit"));
        RechlineEdit->setGeometry(QRect(130, 10, 121, 31));
        RechlineEdit->setFont(font3);
        tableViewAffichage = new QTableView(groupBox_4);
        tableViewAffichage->setObjectName(QStringLiteral("tableViewAffichage"));
        tableViewAffichage->setGeometry(QRect(90, 110, 501, 201));
        tableViewAffichage->setFont(font3);
        rechercheBtn = new QPushButton(groupBox_4);
        rechercheBtn->setObjectName(QStringLiteral("rechercheBtn"));
        rechercheBtn->setGeometry(QRect(140, 70, 111, 28));
        rechercheBtn->setFont(font3);
        sortBtn = new QPushButton(groupBox_4);
        sortBtn->setObjectName(QStringLiteral("sortBtn"));
        sortBtn->setGeometry(QRect(330, 70, 111, 28));
        sortBtn->setFont(font3);
        PDFBtn = new QPushButton(groupBox_4);
        PDFBtn->setObjectName(QStringLiteral("PDFBtn"));
        PDFBtn->setGeometry(QRect(520, 30, 71, 51));
        QFont font5;
        font5.setFamily(QStringLiteral("Arial"));
        font5.setPointSize(12);
        PDFBtn->setFont(font5);
        OpTabWidget->addTab(AFFICHAGE, QString());
        MODIFICATION = new QWidget();
        MODIFICATION->setObjectName(QStringLiteral("MODIFICATION"));
        OpLabel_9 = new QLabel(MODIFICATION);
        OpLabel_9->setObjectName(QStringLiteral("OpLabel_9"));
        OpLabel_9->setGeometry(QRect(0, 0, 781, 491));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        OpLabel_9->setPalette(palette4);
        OpLabel_9->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel_9->setScaledContents(true);
        OpLabel_11 = new QLabel(MODIFICATION);
        OpLabel_11->setObjectName(QStringLiteral("OpLabel_11"));
        OpLabel_11->setGeometry(QRect(30, 110, 321, 21));
        QFont font6;
        font6.setFamily(QStringLiteral("Arial"));
        font6.setPointSize(12);
        font6.setUnderline(false);
        OpLabel_11->setFont(font6);
        OpLabel_11->setStyleSheet(QStringLiteral("background-color: transparent;"));
        OpLabel_12 = new QLabel(MODIFICATION);
        OpLabel_12->setObjectName(QStringLiteral("OpLabel_12"));
        OpLabel_12->setGeometry(QRect(160, 30, 471, 51));
        OpLabel_12->setFont(font1);
        OpLabel_12->setStyleSheet(QStringLiteral("background-color: transparent;"));
        modifSpinBox = new QSpinBox(MODIFICATION);
        modifSpinBox->setObjectName(QStringLiteral("modifSpinBox"));
        modifSpinBox->setGeometry(QRect(500, 100, 171, 31));
        modifSpinBox->setStyleSheet(QStringLiteral("font: 11pt \"Arial\";"));
        OpLabel_13 = new QLabel(MODIFICATION);
        OpLabel_13->setObjectName(QStringLiteral("OpLabel_13"));
        OpLabel_13->setGeometry(QRect(30, 150, 441, 21));
        OpLabel_13->setFont(font6);
        OpLabel_13->setStyleSheet(QStringLiteral("background-color: transparent;"));
        OpLabel_18 = new QLabel(MODIFICATION);
        OpLabel_18->setObjectName(QStringLiteral("OpLabel_18"));
        OpLabel_18->setGeometry(QRect(30, 190, 321, 21));
        OpLabel_18->setFont(font6);
        OpLabel_18->setStyleSheet(QStringLiteral("background-color: transparent;"));
        modifSpinBoxId = new QSpinBox(MODIFICATION);
        modifSpinBoxId->setObjectName(QStringLiteral("modifSpinBoxId"));
        modifSpinBoxId->setGeometry(QRect(500, 140, 171, 31));
        modifSpinBoxId->setStyleSheet(QStringLiteral("font: 11pt \"Arial\";"));
        ModifTypeComboBox = new QComboBox(MODIFICATION);
        ModifTypeComboBox->setObjectName(QStringLiteral("ModifTypeComboBox"));
        ModifTypeComboBox->setGeometry(QRect(500, 180, 171, 31));
        ModifTypeComboBox->setStyleSheet(QStringLiteral("font: 10pt \"Arial\";"));
        OpLabel_20 = new QLabel(MODIFICATION);
        OpLabel_20->setObjectName(QStringLiteral("OpLabel_20"));
        OpLabel_20->setGeometry(QRect(30, 230, 441, 21));
        OpLabel_20->setFont(font6);
        OpLabel_20->setStyleSheet(QStringLiteral("background-color: transparent;"));
        modifDureeLineEdit = new QLineEdit(MODIFICATION);
        modifDureeLineEdit->setObjectName(QStringLiteral("modifDureeLineEdit"));
        modifDureeLineEdit->setGeometry(QRect(500, 220, 171, 31));
        modifDureeLineEdit->setFont(font3);
        modifEtatLineEdit = new QLineEdit(MODIFICATION);
        modifEtatLineEdit->setObjectName(QStringLiteral("modifEtatLineEdit"));
        modifEtatLineEdit->setGeometry(QRect(500, 260, 171, 31));
        modifEtatLineEdit->setFont(font3);
        modifBtn = new QPushButton(MODIFICATION);
        modifBtn->setObjectName(QStringLiteral("modifBtn"));
        modifBtn->setGeometry(QRect(310, 370, 141, 41));
        QFont font7;
        font7.setFamily(QStringLiteral("Arial"));
        font7.setPointSize(14);
        modifBtn->setFont(font7);
        OpLabel_19 = new QLabel(MODIFICATION);
        OpLabel_19->setObjectName(QStringLiteral("OpLabel_19"));
        OpLabel_19->setGeometry(QRect(30, 270, 441, 21));
        OpLabel_19->setFont(font6);
        OpLabel_19->setStyleSheet(QStringLiteral("background-color: transparent;"));
        OpTabWidget->addTab(MODIFICATION, QString());
        SUPPRESSION = new QWidget();
        SUPPRESSION->setObjectName(QStringLiteral("SUPPRESSION"));
        OpLabel_10 = new QLabel(SUPPRESSION);
        OpLabel_10->setObjectName(QStringLiteral("OpLabel_10"));
        OpLabel_10->setGeometry(QRect(0, 0, 781, 491));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        OpLabel_10->setPalette(palette5);
        OpLabel_10->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel_10->setScaledContents(true);
        OpLabel_14 = new QLabel(SUPPRESSION);
        OpLabel_14->setObjectName(QStringLiteral("OpLabel_14"));
        OpLabel_14->setGeometry(QRect(160, 40, 471, 51));
        OpLabel_14->setFont(font1);
        OpLabel_14->setStyleSheet(QStringLiteral("background-color: transparent;"));
        OpLabel_15 = new QLabel(SUPPRESSION);
        OpLabel_15->setObjectName(QStringLiteral("OpLabel_15"));
        OpLabel_15->setGeometry(QRect(30, 190, 361, 21));
        QFont font8;
        font8.setFamily(QStringLiteral("Arial"));
        font8.setPointSize(12);
        font8.setBold(true);
        font8.setUnderline(false);
        font8.setWeight(75);
        OpLabel_15->setFont(font8);
        OpLabel_15->setStyleSheet(QStringLiteral("background-color: transparent;"));
        suppSpinBox = new QSpinBox(SUPPRESSION);
        suppSpinBox->setObjectName(QStringLiteral("suppSpinBox"));
        suppSpinBox->setGeometry(QRect(500, 180, 171, 31));
        suppSpinBox->setStyleSheet(QStringLiteral("font: 11pt \"Arial\";"));
        suppBtn = new QPushButton(SUPPRESSION);
        suppBtn->setObjectName(QStringLiteral("suppBtn"));
        suppBtn->setGeometry(QRect(300, 320, 161, 51));
        QFont font9;
        font9.setPointSize(16);
        suppBtn->setFont(font9);
        OpTabWidget->addTab(SUPPRESSION, QString());
        STATISTIQUE = new QWidget();
        STATISTIQUE->setObjectName(QStringLiteral("STATISTIQUE"));
        OpLabel_22 = new QLabel(STATISTIQUE);
        OpLabel_22->setObjectName(QStringLiteral("OpLabel_22"));
        OpLabel_22->setGeometry(QRect(0, -10, 761, 511));
        OpLabel_22->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel_22->setScaledContents(true);
        OpLabel_23 = new QLabel(STATISTIQUE);
        OpLabel_23->setObjectName(QStringLiteral("OpLabel_23"));
        OpLabel_23->setGeometry(QRect(120, 20, 501, 41));
        QFont font10;
        font10.setFamily(QStringLiteral("Arial"));
        font10.setPointSize(19);
        font10.setBold(false);
        font10.setUnderline(true);
        font10.setWeight(50);
        OpLabel_23->setFont(font10);
        OpLabel_23->setStyleSheet(QStringLiteral("background-color: transparent;"));
        groupBox_5 = new QGroupBox(STATISTIQUE);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(30, 130, 661, 321));
        StatOpTableView = new QTableView(groupBox_5);
        StatOpTableView->setObjectName(QStringLiteral("StatOpTableView"));
        StatOpTableView->setGeometry(QRect(260, 100, 151, 141));
        StatOpTableView->setFont(font3);
        StatTypeBtn = new QPushButton(groupBox_5);
        StatTypeBtn->setObjectName(QStringLiteral("StatTypeBtn"));
        StatTypeBtn->setGeometry(QRect(140, 40, 171, 31));
        StatTypeBtn->setFont(font3);
        statEtatBtn = new QPushButton(groupBox_5);
        statEtatBtn->setObjectName(QStringLiteral("statEtatBtn"));
        statEtatBtn->setGeometry(QRect(360, 40, 171, 31));
        statEtatBtn->setFont(font3);
        OpTabWidget->addTab(STATISTIQUE, QString());
        SUIVI = new QWidget();
        SUIVI->setObjectName(QStringLiteral("SUIVI"));
        OpLabel_26 = new QLabel(SUIVI);
        OpLabel_26->setObjectName(QStringLiteral("OpLabel_26"));
        OpLabel_26->setGeometry(QRect(0, -10, 761, 511));
        OpLabel_26->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel_26->setScaledContents(true);
        OpLabel_30 = new QLabel(SUIVI);
        OpLabel_30->setObjectName(QStringLiteral("OpLabel_30"));
        OpLabel_30->setGeometry(QRect(160, 10, 441, 51));
        OpLabel_30->setFont(font1);
        OpLabel_30->setStyleSheet(QStringLiteral("background-color: transparent;"));
        groupBox_6 = new QGroupBox(SUIVI);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(40, 130, 651, 321));
        SuiviBtn = new QPushButton(groupBox_6);
        SuiviBtn->setObjectName(QStringLiteral("SuiviBtn"));
        SuiviBtn->setGeometry(QRect(330, 80, 111, 41));
        SuiviBtn->setFont(font3);
        suiviLineEdit = new QLineEdit(groupBox_6);
        suiviLineEdit->setObjectName(QStringLiteral("suiviLineEdit"));
        suiviLineEdit->setGeometry(QRect(190, 80, 91, 41));
        stackedWidget_2 = new QStackedWidget(groupBox_6);
        stackedWidget_2->setObjectName(QStringLiteral("stackedWidget_2"));
        stackedWidget_2->setGeometry(QRect(370, 160, 51, 41));
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        page_5->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        stackedWidget_2->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        page_6->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 0);"));
        stackedWidget_2->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        page_7->setStyleSheet(QLatin1String("color: rgb(85, 255, 127);\n"
"background-color: rgb(85, 255, 127);"));
        stackedWidget_2->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName(QStringLiteral("page_8"));
        stackedWidget_2->addWidget(page_8);
        OpLabel_16 = new QLabel(groupBox_6);
        OpLabel_16->setObjectName(QStringLiteral("OpLabel_16"));
        OpLabel_16->setGeometry(QRect(210, 210, 201, 41));
        OpLabel_16->setFont(font5);
        OpLabel_16->setStyleSheet(QStringLiteral(""));
        OpLabel_21 = new QLabel(groupBox_6);
        OpLabel_21->setObjectName(QStringLiteral("OpLabel_21"));
        OpLabel_21->setGeometry(QRect(160, 160, 171, 41));
        OpLabel_21->setFont(font5);
        OpLabel_21->setStyleSheet(QStringLiteral(""));
        OpTabWidget->addTab(SUIVI, QString());
        ACCEPTER_OPERATION = new QWidget();
        ACCEPTER_OPERATION->setObjectName(QStringLiteral("ACCEPTER_OPERATION"));
        OpLabel_27 = new QLabel(ACCEPTER_OPERATION);
        OpLabel_27->setObjectName(QStringLiteral("OpLabel_27"));
        OpLabel_27->setGeometry(QRect(0, -10, 761, 511));
        OpLabel_27->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel_27->setScaledContents(true);
        groupBox_7 = new QGroupBox(ACCEPTER_OPERATION);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(80, 140, 571, 271));
        OpLabel_24 = new QLabel(groupBox_7);
        OpLabel_24->setObjectName(QStringLiteral("OpLabel_24"));
        OpLabel_24->setGeometry(QRect(50, 40, 491, 41));
        OpLabel_24->setFont(font2);
        OpLabel_24->setStyleSheet(QStringLiteral(""));
        OpLabel_25 = new QLabel(groupBox_7);
        OpLabel_25->setObjectName(QStringLiteral("OpLabel_25"));
        OpLabel_25->setGeometry(QRect(20, 140, 541, 41));
        OpLabel_25->setFont(font7);
        OpLabel_25->setStyleSheet(QStringLiteral(""));
        AccepteOpBtn = new QPushButton(groupBox_7);
        AccepteOpBtn->setObjectName(QStringLiteral("AccepteOpBtn"));
        AccepteOpBtn->setGeometry(QRect(200, 210, 181, 31));
        AccepteOpBtn->setFont(font3);
        OpLabel_31 = new QLabel(ACCEPTER_OPERATION);
        OpLabel_31->setObjectName(QStringLiteral("OpLabel_31"));
        OpLabel_31->setGeometry(QRect(170, 20, 441, 51));
        OpLabel_31->setFont(font1);
        OpLabel_31->setStyleSheet(QStringLiteral("background-color: transparent;"));
        OpTabWidget->addTab(ACCEPTER_OPERATION, QString());
        MESUREDEPOIDS = new QWidget();
        MESUREDEPOIDS->setObjectName(QStringLiteral("MESUREDEPOIDS"));
        OpLabel_28 = new QLabel(MESUREDEPOIDS);
        OpLabel_28->setObjectName(QStringLiteral("OpLabel_28"));
        OpLabel_28->setGeometry(QRect(0, -10, 761, 511));
        OpLabel_28->setPixmap(QPixmap(QString::fromUtf8("../../../jewelry.jpg")));
        OpLabel_28->setScaledContents(true);
        groupBox_8 = new QGroupBox(MESUREDEPOIDS);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(60, 140, 641, 301));
        OpLabel_29 = new QLabel(groupBox_8);
        OpLabel_29->setObjectName(QStringLiteral("OpLabel_29"));
        OpLabel_29->setGeometry(QRect(40, 80, 341, 41));
        QFont font11;
        font11.setFamily(QStringLiteral("Arial"));
        font11.setPointSize(11);
        font11.setBold(false);
        font11.setWeight(50);
        OpLabel_29->setFont(font11);
        lineEdit_5 = new QLineEdit(groupBox_8);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(420, 90, 151, 22));
        pushButton_12 = new QPushButton(groupBox_8);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(260, 180, 121, 41));
        OpLabel_32 = new QLabel(MESUREDEPOIDS);
        OpLabel_32->setObjectName(QStringLiteral("OpLabel_32"));
        OpLabel_32->setGeometry(QRect(190, 40, 351, 51));
        OpLabel_32->setFont(font1);
        OpLabel_32->setStyleSheet(QStringLiteral("background-color: transparent;"));
        OpTabWidget->addTab(MESUREDEPOIDS, QString());
        stackedWidget->addWidget(page_3);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1134, 26));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(2);
        tabWidget->setCurrentIndex(1);
        ajouter->setCurrentIndex(0);
        OpTabWidget->setCurrentIndex(0);
        stackedWidget_2->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Gestion des Clients", Q_NULLPTR));
        pushButton->setText(QApplication::translate("MainWindow", "GESTION DE COMMANDES", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("MainWindow", "GESTION DE PRODUITS", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("MainWindow", "GESTION D'OPERATIONS", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", "Ajout d'un etudiant", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "Identifiant", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "Prix", Q_NULLPTR));
        pb_ajouter->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        pb_modifier->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        comboBoxCategory->clear();
        comboBoxCategory->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Categorie  +", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Collier", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Boucles", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Anneau", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Bracelet", Q_NULLPTR)
        );
        label_5->setText(QApplication::translate("MainWindow", "quantite", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        checkBox->setText(QApplication::translate("MainWindow", "Anneau", Q_NULLPTR));
        checkBox_2->setText(QApplication::translate("MainWindow", "Bracelet", Q_NULLPTR));
        checkBox_3->setText(QApplication::translate("MainWindow", "Boucles", Q_NULLPTR));
        checkBox_4->setText(QApplication::translate("MainWindow", "Collier", Q_NULLPTR));
        pushButtonGenererPDF->setText(QApplication::translate("MainWindow", "Print", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Afficher", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "id", Q_NULLPTR));
        pb_supprimer->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("MainWindow", "HOME", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        pushButtonStatsCategorie->setText(QApplication::translate("MainWindow", "Stats", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_9), QApplication::translate("MainWindow", "Statistique", Q_NULLPTR));
        pushButtonAfficherAlertes->setText(QApplication::translate("MainWindow", "Visualiser", Q_NULLPTR));
        pushButtonAjouterStock->setText(QApplication::translate("MainWindow", "Commander manque", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Alertes", Q_NULLPTR));
        label_16->setText(QString());
        groupBox_3->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", " L'identifiant", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "le produit", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Numero de telephone", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "typePaiment", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "Id produit", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "date_", Q_NULLPTR));
        calculatePaymentStatistics->clear();
        calculatePaymentStatistics->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "enligne", Q_NULLPTR)
         << QApplication::translate("MainWindow", "cheque", Q_NULLPTR)
         << QApplication::translate("MainWindow", "carte", Q_NULLPTR)
        );
        pb_valider->setText(QApplication::translate("MainWindow", "Valider", Q_NULLPTR));
        modif_2->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Prix", Q_NULLPTR));
        recherche_2->setText(QApplication::translate("MainWindow", "rechercher", Q_NULLPTR));
        comboBox_3->clear();
        comboBox_3->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "id", Q_NULLPTR)
         << QApplication::translate("MainWindow", "nom", Q_NULLPTR)
         << QApplication::translate("MainWindow", "prenom", Q_NULLPTR)
        );
        tri_2->setText(QApplication::translate("MainWindow", "trier", Q_NULLPTR));
        comboBox_4->clear();
        comboBox_4->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "id", Q_NULLPTR)
         << QApplication::translate("MainWindow", "nom", Q_NULLPTR)
         << QApplication::translate("MainWindow", "prenom", Q_NULLPTR)
        );
        exel_2->setText(QApplication::translate("MainWindow", "exel", Q_NULLPTR));
        historique_2->setText(QApplication::translate("MainWindow", "hisorique", Q_NULLPTR));
        pdf_2->setText(QApplication::translate("MainWindow", "pdf", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "entrer l'id", Q_NULLPTR));
        supp_3->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("MainWindow", "HOME", Q_NULLPTR));
        ajouter->setTabText(ajouter->indexOf(tab_6), QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        ajouter->setTabText(ajouter->indexOf(Afficher), QApplication::translate("MainWindow", "calendrier", Q_NULLPTR));
        pushButtonstat->setText(QApplication::translate("MainWindow", "Statestique", Q_NULLPTR));
        ajouter->setTabText(ajouter->indexOf(tab_7), QApplication::translate("MainWindow", "Statistique", Q_NULLPTR));
        envoyer->setText(QApplication::translate("MainWindow", "envoyer", Q_NULLPTR));
        label_chatbot_response->setText(QString());
        ajouter->setTabText(ajouter->indexOf(chat), QApplication::translate("MainWindow", "chat", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "Lampe1", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "Lampe2", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("MainWindow", "+", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("MainWindow", "ON", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("MainWindow", "OFF", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "Etat lampe", Q_NULLPTR));
        label_21->setText(QString());
        pushButton_5->setText(QApplication::translate("MainWindow", "-", Q_NULLPTR));
        ajouter->setTabText(ajouter->indexOf(tab_8), QApplication::translate("MainWindow", "Page", Q_NULLPTR));
        OpLabel->setText(QString());
        OpLabel_6->setText(QApplication::translate("MainWindow", "(par jours)*", Q_NULLPTR));
        OpLabel_2->setText(QApplication::translate("MainWindow", "Cr\303\251ation d'une op\303\251ration", Q_NULLPTR));
        OpLabel_4->setText(QApplication::translate("MainWindow", "- TYPE d'op\303\251ration :", Q_NULLPTR));
        OpLabel_3->setText(QApplication::translate("MainWindow", "- ID d'op\303\251ration :", Q_NULLPTR));
        typeComboBox->clear();
        typeComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "CHOISIR LE TYPE D'OPERATION", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Fabrication", Q_NULLPTR)
         << QApplication::translate("MainWindow", "R\303\251paration", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Ajustement", Q_NULLPTR)
        );
        OpLabel_5->setText(QApplication::translate("MainWindow", "- Dur\303\251e maximale d'op\303\251ration :", Q_NULLPTR));
        OpLabel_17->setText(QApplication::translate("MainWindow", "- Entrer l'etat de l'operation:", Q_NULLPTR));
        creationBtn->setText(QApplication::translate("MainWindow", "valider", Q_NULLPTR));
        OpTabWidget->setTabText(OpTabWidget->indexOf(CREATION), QApplication::translate("MainWindow", "CREATION", Q_NULLPTR));
        OpLabel_7->setText(QString());
        OpLabel_8->setText(QApplication::translate("MainWindow", "Votre Op\303\251rations", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        choixComboBox->clear();
        choixComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "PAR DEFAUT", Q_NULLPTR)
         << QApplication::translate("MainWindow", "numero_operation", Q_NULLPTR)
         << QApplication::translate("MainWindow", "ETAT", Q_NULLPTR)
         << QApplication::translate("MainWindow", "DUREE", Q_NULLPTR)
        );
        rechercheBtn->setText(QApplication::translate("MainWindow", "recherche", Q_NULLPTR));
        sortBtn->setText(QApplication::translate("MainWindow", "TRI", Q_NULLPTR));
        PDFBtn->setText(QApplication::translate("MainWindow", "PDF", Q_NULLPTR));
        OpTabWidget->setTabText(OpTabWidget->indexOf(AFFICHAGE), QApplication::translate("MainWindow", "AFFICHAGE", Q_NULLPTR));
        OpLabel_9->setText(QString());
        OpLabel_11->setText(QApplication::translate("MainWindow", "* Entrer l'id d'op\303\251ration \303\240 modifier :", Q_NULLPTR));
        OpLabel_12->setText(QApplication::translate("MainWindow", "Modification d'une op\303\251ration", Q_NULLPTR));
        OpLabel_13->setText(QApplication::translate("MainWindow", "* Entrer le nouveau id:", Q_NULLPTR));
        OpLabel_18->setText(QApplication::translate("MainWindow", "* Entrer le nouveau type :", Q_NULLPTR));
        ModifTypeComboBox->clear();
        ModifTypeComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Choisir une option", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Fabrication", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Ajustement", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Reparation", Q_NULLPTR)
        );
        OpLabel_20->setText(QApplication::translate("MainWindow", "* Entrer la nouvelle duree:", Q_NULLPTR));
        modifBtn->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        OpLabel_19->setText(QApplication::translate("MainWindow", "* Entrer la nouvelle etat:", Q_NULLPTR));
        OpTabWidget->setTabText(OpTabWidget->indexOf(MODIFICATION), QApplication::translate("MainWindow", "MODIFICATION", Q_NULLPTR));
        OpLabel_10->setText(QString());
        OpLabel_14->setText(QApplication::translate("MainWindow", "Supprission d'une op\303\251ration", Q_NULLPTR));
        OpLabel_15->setText(QApplication::translate("MainWindow", "* Entrer l'id d'op\303\251ration \303\240 supprimer :", Q_NULLPTR));
        suppBtn->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        OpTabWidget->setTabText(OpTabWidget->indexOf(SUPPRESSION), QApplication::translate("MainWindow", "SUPPRESSION", Q_NULLPTR));
        OpLabel_22->setText(QString());
        OpLabel_23->setText(QApplication::translate("MainWindow", "STATISTIQUE DES OPERATIONS", Q_NULLPTR));
        groupBox_5->setTitle(QString());
        StatTypeBtn->setText(QApplication::translate("MainWindow", "statistique par type", Q_NULLPTR));
        statEtatBtn->setText(QApplication::translate("MainWindow", "statistique par etat", Q_NULLPTR));
        OpTabWidget->setTabText(OpTabWidget->indexOf(STATISTIQUE), QApplication::translate("MainWindow", "STATISTIQUE", Q_NULLPTR));
        OpLabel_26->setText(QString());
        OpLabel_30->setText(QApplication::translate("MainWindow", "SUIVI DES OPERATIONS", Q_NULLPTR));
        groupBox_6->setTitle(QString());
        SuiviBtn->setText(QApplication::translate("MainWindow", "AFFICHER", Q_NULLPTR));
        OpLabel_16->setText(QString());
        OpLabel_21->setText(QString());
        OpTabWidget->setTabText(OpTabWidget->indexOf(SUIVI), QApplication::translate("MainWindow", "SUIVI", Q_NULLPTR));
        OpLabel_27->setText(QString());
        groupBox_7->setTitle(QString());
        OpLabel_24->setText(QString());
        OpLabel_25->setText(QString());
        AccepteOpBtn->setText(QApplication::translate("MainWindow", "AFFICHER DETAILS", Q_NULLPTR));
        OpLabel_31->setText(QApplication::translate("MainWindow", "ACCEPT AUTOMATIQUE", Q_NULLPTR));
        OpTabWidget->setTabText(OpTabWidget->indexOf(ACCEPTER_OPERATION), QApplication::translate("MainWindow", "ACCEPTER OPERATION", Q_NULLPTR));
        OpLabel_28->setText(QString());
        groupBox_8->setTitle(QString());
        OpLabel_29->setText(QApplication::translate("MainWindow", "ENTRER L'ID DU PRODUIT A MESURER:", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("MainWindow", "confirmer", Q_NULLPTR));
        OpLabel_32->setText(QApplication::translate("MainWindow", "MESURE DE POIDS", Q_NULLPTR));
        OpTabWidget->setTabText(OpTabWidget->indexOf(MESUREDEPOIDS), QApplication::translate("MainWindow", "MESURE DE POIDS", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
